version: "3.8"

services:
  users-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: users-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://users-db:5432/users
      SPRING_DATASOURCE_USERNAME: users
      SPRING_DATASOURCE_PASSWORD: users
    depends_on:
      users-db:
        condition: service_healthy
    restart: unless-stopped

  users-db:
    image: postgres:16-alpine
    container_name: users-db
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: users
      POSTGRES_PASSWORD: users
    ports:
      - "5432:5432"
    volumes:
      - users-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U users -d users"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: users-postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://users:users@users-db:5432/users?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      users-db:
        condition: service_healthy
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: users-node-exporter
    command:
      - "--path.rootfs=/host"
    volumes:
      - "/:/host:ro,rslave"
    ports:
      - "9100:9100"
    restart: unless-stopped

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.25.0
    container_name: users-blackbox-exporter
    ports:
      - "9115:9115"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./ops/blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml:ro
    command:
      - "--config.file=/etc/blackbox_exporter/config.yml"
    restart: unless-stopped

  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.8.0
    container_name: users-kafka-exporter
    command:
      - "--kafka.server=${KAFKA_BOOTSTRAP_SERVERS:-host.docker.internal:9092}"
      - "--web.listen-address=:9308"
    ports:
      - "9308:9308"
    restart: unless-stopped


  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: users-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro # ro - read only для того, чтобы prometheus не мог сам изменить этот файл внутри контейнера
      - ./ops/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
      - prometheus-data:/prometheus # Объявляем volume для хранения данных prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml # Указываем файл с конфигурацией prometheus, в которой будут конфиги для scrape jobs
      - --storage.tsdb.path=/prometheus # Указываем директорию для хранения данных prometheus. Причем мы перед этим завели volume как раз для этой директории, чтобы данные не потерялись
      - --storage.tsdb.retention.time=15d # Указываем время хранения данных prometheus. По умолчанию 15 дней
    extra_hosts:
      - "host.docker.internal:host-gateway" # В контейнере появляется запись в /etc/hosts, которая позволяет обращаться к хосту по имени host.docker.internal, а не по ip адресу. А сам host-gateway - это специальное значение docker daemon, которое позволяет обращаться к хосту по ip адресу, но не используя хардкор ip адрес
    restart: unless-stopped # Политика перезапуска контейнера. Если контейнер упал, то он будет перезапущен или если мы перезагрузили сам компьютер, то при включении docker daemon такой контейнер так же будет поднят. Не будет поднят, только если явно сами руками остановим его

  grafana:
    image: grafana/grafana:11.1.0
    container_name: users-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      # Стоит обратить внимание на /etс и /var. Обычно принято в /etc сохранять конфигурационные файлы. А в /var/lib/<libName> какие-то файлы состояния или runtime. Поэтому provisioning мы кладем в /etc, т.к. это конфигурации для старта grafana. А вот dashboards уже конкретные, которые используется в работе кладем в /var/lib
      - ./ops/grafana/provisioning:/etc/grafana/provisioning:ro # Данный путь является дефолтным для чтения grafan-ой настроек. В provisioning мы прописываем инструкции для Grafanfa при ее старте. Например, datasource и dashboard providers откуда читать json dashboards
      - ./ops/grafana/dashboards:/var/lib/grafana/dashboards:ro # А эта уже папка с самими json для dashboards, которые мы не хотим потерять при поднятии grafana с нуля. Grafanfa не читает данную папку по умолчанию, она делает это через dashboard provider, который настраивается в provisioning 
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  users-db-data:
  prometheus-data:
  grafana-data:

