--liquibase formatted sql

--changeset AVSmirnov:0001-1
CREATE SCHEMA IF NOT EXISTS users;

--changeset AVSmirnov:0001-2
--comment: Структура ВУЗа: Факультеты, Кафедры, Направления

-- 1. Факультеты / Институты
CREATE TABLE IF NOT EXISTS users.faculties (
                                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               name VARCHAR(255) NOT NULL,           -- Например: "Институт информационных технологий"
                                               short_name VARCHAR(50) NOT NULL,
                                               created_at TIMESTAMP NOT NULL,
                                               created_by VARCHAR(255) NOT NULL,
                                               updated_at TIMESTAMP NOT NULL,
                                               updated_by VARCHAR(255) NOT NULL
);

-- 2. Кафедры (Привязаны к факультету)
CREATE TABLE IF NOT EXISTS users.departments (
                                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 name VARCHAR(255) NOT NULL,           -- Например: "Кафедра прикладной математики"
                                                 faculty_id BIGINT NOT NULL,
                                                 created_at TIMESTAMP NOT NULL,
                                                 created_by VARCHAR(255) NOT NULL,
                                                 updated_at TIMESTAMP NOT NULL,
                                                 updated_by VARCHAR(255) NOT NULL,
                                                 CONSTRAINT fk_departments_faculty FOREIGN KEY (faculty_id)
                                                     REFERENCES users.faculties (id) ON DELETE RESTRICT
);

-- 3. Направления подготовки (НОВАЯ СУЩНОСТЬ)
-- Студент поступает на направление внутри факультета.
CREATE TABLE IF NOT EXISTS users.fields_of_study (
                                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                     code VARCHAR(20) NOT NULL,            -- Например: "09.03.04"
                                                     name VARCHAR(255) NOT NULL,           -- Например: "Программная инженерия"
                                                     faculty_id BIGINT NOT NULL,           -- Направление курирует факультет
                                                     created_at TIMESTAMP NOT NULL,
                                                     created_by VARCHAR(255) NOT NULL,
                                                     updated_at TIMESTAMP NOT NULL,
                                                     updated_by VARCHAR(255) NOT NULL,
                                                     CONSTRAINT fk_fields_faculty FOREIGN KEY (faculty_id)
                                                         REFERENCES users.faculties (id) ON DELETE RESTRICT
);

-- 4. Учебные группы
-- Группа привязана к факультету и конкретному направлению подготовки.
-- Группа НЕ привязана к кафедре жестко, так как студенты внутри могут быть с разных кафедр.
CREATE TABLE IF NOT EXISTS users.student_groups (
                                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                    name VARCHAR(50) NOT NULL,            -- Например: "ИВТ-401"
                                                    faculty_id BIGINT NOT NULL,           -- Административная привязка (деканат)
                                                    field_of_study_id BIGINT NOT NULL,    -- Какую программу изучают
                                                    created_at TIMESTAMP NOT NULL,
                                                    created_by VARCHAR(255) NOT NULL,
                                                    updated_at TIMESTAMP NOT NULL,
                                                    updated_by VARCHAR(255) NOT NULL,
                                                    CONSTRAINT fk_groups_faculty FOREIGN KEY (faculty_id)
                                                        REFERENCES users.faculties (id) ON DELETE RESTRICT,
                                                    CONSTRAINT fk_groups_field FOREIGN KEY (field_of_study_id)
                                                        REFERENCES users.fields_of_study (id) ON DELETE RESTRICT
);

--changeset AVSmirnov:0001-3
--comment: Базовая таблица пользователей и ролей

CREATE TABLE IF NOT EXISTS users.users (
                                           id UUID PRIMARY KEY,
                                           username VARCHAR(255) NOT NULL UNIQUE, -- логин при аутентификации. Для студентов - это номер студ билета. Для преподавателей может быть табельник сотрудника(в бухгалтерии всем присваивается). Для админа будет admin
                                           email VARCHAR(255) UNIQUE,
                                           password VARCHAR(255) NOT NULL, -- хранит хеш пароля в формате {bcrypt}... для Spring DelegatingPasswordEncoder
                                           first_name VARCHAR(100) NOT NULL,
                                           last_name VARCHAR(100) NOT NULL,
                                           middle_name VARCHAR(100),
                                           is_active BOOLEAN DEFAULT TRUE NOT NULL,
                                           created_at TIMESTAMP NOT NULL,
                                           created_by VARCHAR(255) NOT NULL,
                                           updated_at TIMESTAMP NOT NULL,
                                           updated_by VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS users.roles (
                                           id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users.users_roles (
                                                 user_id UUID NOT NULL,
                                                 role_id INT NOT NULL,
                                                 PRIMARY KEY (user_id, role_id),
                                                 created_at TIMESTAMP NOT NULL,
                                                 created_by VARCHAR(255) NOT NULL,
                                                 updated_at TIMESTAMP NOT NULL,
                                                 updated_by VARCHAR(255) NOT NULL,
                                                 CONSTRAINT fk_users_roles_user FOREIGN KEY (user_id)
                                                     REFERENCES users.users (id) ON DELETE CASCADE,
                                                 CONSTRAINT fk_users_roles_role FOREIGN KEY (role_id)
                                                     REFERENCES users.roles (id) ON DELETE CASCADE
);

--changeset AVSmirnov:0001-4
--comment: Профили с обновленной логикой связей

-- ПРОФИЛЬ СТУДЕНТА
CREATE TABLE IF NOT EXISTS users.student_profiles (
                                                      user_id UUID PRIMARY KEY,
                                                      group_id BIGINT NOT NULL,             -- Обязательно: студент должен быть в группе
                                                      department_id BIGINT,                 -- NULLABLE! Студент может не иметь кафедры (1-2 курс)
                                                      created_at TIMESTAMP NOT NULL,
                                                      created_by VARCHAR(255) NOT NULL,
                                                      updated_at TIMESTAMP NOT NULL,
                                                      updated_by VARCHAR(255) NOT NULL,

                                                      CONSTRAINT fk_student_profile_user FOREIGN KEY (user_id)
                                                          REFERENCES users.users (id) ON DELETE CASCADE,
                                                      CONSTRAINT fk_student_profile_group FOREIGN KEY (group_id)
                                                          REFERENCES users.student_groups (id) ON DELETE RESTRICT,
    -- Важно: Студент выбирает кафедру индивидуально.
    -- Это позволяет студентам одной группы (group_id) иметь разные department_id.
                                                      CONSTRAINT fk_student_profile_dept FOREIGN KEY (department_id)
                                                          REFERENCES users.departments (id) ON DELETE SET NULL
);

-- ПРОФИЛЬ ПРЕПОДАВАТЕЛЯ (Базовый)
CREATE TABLE IF NOT EXISTS users.teacher_profiles (
                                                      user_id UUID PRIMARY KEY,
                                                      department_id BIGINT NOT NULL,
                                                      created_at TIMESTAMP NOT NULL,
                                                      created_by VARCHAR(255) NOT NULL,
                                                      updated_at TIMESTAMP NOT NULL,
                                                      updated_by VARCHAR(255) NOT NULL,

                                                      CONSTRAINT fk_teacher_profile_user FOREIGN KEY (user_id)
                                                          REFERENCES users.users (id) ON DELETE CASCADE,

                                                      CONSTRAINT fk_teacher_profile_department FOREIGN KEY (department_id)
                                                          REFERENCES users.departments(id) ON DELETE RESTRICT -- запрещаем удаление кафедры без явного удаления учителя
);



--changeset AVSmirnov:0001-5
--comment: Индексы

CREATE INDEX IF NOT EXISTS idx_users_email ON users.users(email);
CREATE INDEX IF NOT EXISTS idx_users_username ON users.users(username);
CREATE INDEX IF NOT EXISTS idx_departments_faculty ON users.departments(faculty_id);
CREATE INDEX IF NOT EXISTS idx_fields_of_study_faculty ON users.fields_of_study(faculty_id);
CREATE INDEX IF NOT EXISTS idx_students_groups_faculty ON users.student_groups(faculty_id);
CREATE INDEX IF NOT EXISTS idx_students_groups_field ON users.student_groups(field_of_study_id);

CREATE INDEX IF NOT EXISTS idx_student_profiles_group ON users.student_profiles(group_id);
CREATE INDEX IF NOT EXISTS idx_student_profiles_department ON users.student_profiles(department_id);
CREATE INDEX IF NOT EXISTS idx_teacher_profiles_department ON users.teacher_profiles(department_id);


--changeset AVSmirnov:0001-6
INSERT INTO users.roles (name) VALUES ('ROLE_STUDENT'), ('ROLE_TEACHER'), ('ROLE_ADMIN')
ON CONFLICT (name) DO NOTHING;