spring:
  application:
    name: users

  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: users
    password: users
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/users-changelog-master.yml
    enabled: true

server:
  port: 8080
tokens:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    access:
      expiration: 10m
    claim:
      roles: roles # field name in jwt token

  refresh:
    expiration: 30d
    tokensForOneUser: 5
  resetPassword:
    length: 15
    expiration: 15m